<?php
/**
 * Mageplace Freshdesk extension
 *
 * @category    Mageplace_Freshdesk
 * @package     Mageplace_Freshdesk
 * @copyright   Copyright (c) 2014 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */

/**
 * @see  Mageplace_Freshdesk_Block_Field_Custom_Checkbox
 *
 * @var Mageplace_Freshdesk_Block_Field_Custom_Checkbox $this
 */

?>
<input type="checkbox" id="<?php echo $this->getFieldId(); ?>" name="<?php echo $this->getFieldName(); ?>"
       class="<?php echo $this->getFieldClass(); ?>" value="1"/>