<?php
/**
 * Mageplace Freshdesk extension
 *
 * @category    Mageplace_Freshdesk
 * @package     Mageplace_Freshdesk
 * @copyright   Copyright (c) 2014 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */

/**
 * @see Mageplace_Freshdesk_Block_Field_Paragraph
 *
 * @var Mageplace_Freshdesk_Block_Field_Paragraph $this
 */

echo $this->getEditor()->toHtml();
/*?>
<textarea id="<?php echo $this->getFieldId(); ?>" name="<?php echo $this->getFieldName(); ?>"
          class="<?php echo $this->getFieldClass(); ?>" rows="2" cols="15"></textarea>
<?php */