<?php
/**
 * Mageplace Freshdesk extension
 *
 * @category    Mageplace_Freshdesk
 * @package     Mageplace_Freshdesk
 * @copyright   Copyright (c) 2014 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */

/**
 * @see  Mageplace_Freshdesk_Block_Field_Row
 *
 * @var Mageplace_Freshdesk_Block_Field_Row $this
 */

?>
<li class="control">
    <?php echo $this->getInputFieldHtml(); ?>
    <label for="<?php echo $this->getFieldId(); ?>"
           class="<?php if ($this->isRequired()): ?>required<?php endif; ?>">
        <?php if ($this->isRequired()): ?> <em class="required">*</em><?php endif; ?>
        <?php echo $this->getFieldLabel(); ?>
    </label>
</li>
