<?php
/**
 * Mageplace Freshdesk extension
 *
 * @category    Mageplace_Freshdesk
 * @package     Mageplace_Freshdesk
 * @copyright   Copyright (c) 2014 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */

/**
 * @see  Mageplace_Freshdesk_Block_Field_Row
 *
 * @var Mageplace_Freshdesk_Block_Field_Row $this
 */

?>
<tr>
    <td class="label">
        <label for="<?php echo $this->getFieldId(); ?>">
            <?php echo $this->getFieldLabel(); ?>
            <?php if ($this->isRequired()): ?> <span class="required">*</span><?php endif; ?>
        </label>
    </td>
    <td class="value">
        <?php echo $this->getInputFieldHtml(); ?>
    </td>
</tr>
