<?php
/**
 * Mageplace Freshdesk extension
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2014 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */
?>
<span class="separator">|</span>
<a href="<?php echo $this->getCreateTicketUrl() ?>" class="link-create-order">
    <?php echo Mage::helper('freshdesk')->__('Create a Ticket') ?>
</a>